apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: sayan3sarkar/ticketing-tickets-service
          env:
            - name: MONGO_URI
              value: "mongodb://tickets-mongo-svc"
            - name: DB_NAME
              value: "tickets"
            - name: MONGO_PORT
              value: "27017"
            - name: TICKETS_PORT
              value: "3000"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          # imagePullPolicy: Never
